language: r
dist: trusty
sudo: false
r: devel
cache: packages

latex: true


matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: 
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - llvm-5.0-dev
            - binutils-gold 
      env:
        - MATRIX_EVAL="CXX=clang++-5.0"


before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir -p ~/.R/
  - echo "CXX = `R CMD config CXX`" >> ~/.R/Makevars
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -pedantic -g0 -flto" >> ~/.R/Makevars
  - echo "LDFLAGS += -flto" >> ~/.R/Makevars
  - echo "LDFLAGS += -fuse-ld=gold" >> ~/.R/Makevars
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ~/.R/Makevars
  - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ~/.R/Makevars

script: 
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check bamr*tar.gz

after_script:
  - tar -ztvf bamr_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - travis_wait 40 Rscript -e 'covr::codecov()'

after_failure:
  - cat bamr.Rcheck/00*
